import{S as u,i as c}from"./assets/vendor-46aac873.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerpolicy&&(o.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?o.credentials="include":e.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const m=document.querySelector(".form");m.addEventListener("submit",h);const a=document.querySelector(".gallery"),l=document.querySelector(".loader"),f="https://pixabay.com/api",g="11329962-6436ba51ddb58bb96deed169a";function h(i){i.preventDefault(),a.innerHTML="",l.classList.add("is-visible");const r=i.currentTarget,t=r.elements.searchTerm.value;console.log(t),d(t).then(s=>{if(console.log(s.hits),s.hits==0)y();else{let e="";for(const n of s.hits)e+=p(n);a.innerHTML=e,new u(".gallery a").refresh()}}).catch(b()).finally(()=>r.reset())}function d(i){const r=new URLSearchParams({key:g,q:i,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:9});return fetch(`${f}/?${r}`).then(t=>{if(!t.ok)throw new Error(t.statusText);return t.json()})}function p({webformatURL:i,largeImageURL:r,tags:t,likes:s,views:e,comments:o,downloads:n}){return`<li class="gallery-item">
    <a class="gallery-link" href="${r}">
        <img class="gallery-image" src="${i}" alt="${t}" />
    </a>
    <div class="image-details">
        <p>Likes </br> ${s}</p>
        <p>Views </br>  ${e}</p>
        <p>Comments </br>  ${o}</p>
        <p>Downloads </br>  ${n}</p>
    </div>
    </li>`}function y(){c.show({position:"topRight",messageColor:"white",iconUrl:"error.svg",iconColor:"white",color:"#EF4040",message:"Sorry, there are no images matching your search query. Please try again!"}),l.classList.remove("is-visible")}function b(){c.show({position:"topRight",messageColor:"white",iconUrl:"error.svg",iconColor:"white",color:"#EF4040",message:"Whoops, something went wrong!"}),l.classList.remove("is-visible")}
//# sourceMappingURL=commonHelpers.js.map
